# Generated by Django 5.1.7 on 2025-03-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="long_description",
            field=models.TextField(default="..."),
        ),
    ]
